# cp ~/.config/alacritty/alacritty.toml /mnt/c/Users/username/AppData/Roaming/alacritty
# hello

# Colours (Monokai Charcoal)

# Default Colours
[colors.primary]
background = '#000000'
foreground = '#FFFFFF'

# Normal Colours
[colors.normal]
black   = '#1a1a1a'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#fa8419'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#c4c5b5'

# Bright Colours
[colors.bright]
black   = '#625e4c'
red     = '#f4005f'
green   = '#98e024'
yellow  = '#e0d561'
blue    = '#9d65ff'
magenta = '#f4005f'
cyan    = '#58d1eb'
white   = '#f6f6ef'

[terminal.shell]
program = "wsl.exe"

[window]
startup_mode = "Maximized" 
opacity = 0.97
decorations = "None"

[font]
normal.family = "OpendyslexicM Nerd Font Mono"
bold.family = "OpendyslexicM Nerd Font Mono"
italic.family = "OpendyslexicM Nerd Font Mono"
bold_italic.family = "OpendyslexicM Nerd Font Mono"
size = 7.0
