# cp ~/.config/alacritty/alacritty.toml /mnt/c/Users/khars/AppData/Roaming/alacritty
[shell]
program = "wsl.exe"
# args = [ "~/.nix-profile/bin/zsh", "-c ", "cd ~ && ~/.config/bin/tx" ]


[window]
startup_mode = "Maximized" 
opacity = 0.97

[font]
normal.family = "MesloLGS Nerd Font Propo"
bold.family = "MesloLGS Nerd Font Propo"
italic.family = "MesloLGS Nerd Font Propo"
bold_italic.family = "MesloLGS Nerd Font Propo"
size = 13.0

