augroup highlight_yank
    autocmd!
    au TextYankPost * silent! lua vim.highlight.on_yank{higroup="IncSearch", timeout=700}
augroup END

" Scrathpad
    augroup scratchpad_pdf
        autocmd!
        autocmd BufwritePost */notes/scratch/scrathpad.md :silent !pandoc ~/notes/scratch/scrathpad.md --pdf-engine=xelatex -o ~/Downloads/scratchpad.pdf --resource-path=$(echo $HOME)/notes/scratch
    augroup END

    :command Scrathpad           :e ~/notes/scratch/scrathpad.md
    :command ScrathpadPDF        !xdg-open ~/Downloads/scratchpad.pdf
    :command Rough               :e ~/notes/scratch/rough.md

nnoremap <silent> <leader>f      :NvimTreeToggle<cr>

" Telescope
    nnoremap <leader>?           :lua require('telescope.builtin').oldfiles()<cr>
    nnoremap <leader>s           :lua require('telescope.builtin').buffers()<cr>
    nnoremap <leader>gf          :lua require('telescope.builtin').git_files()<cr>
    nnoremap <leader>sf          :lua require('telescope.builtin').find_files()<cr>
    nnoremap <leader>sh          :lua require('telescope.builtin').help_tags()<cr>
    nnoremap <leader>*           :lua require('telescope.builtin').grep_string()<cr>
    nnoremap <leader><leader>*   :lua require('telescope.builtin').grep_string()<cr><C-q>
    nnoremap <leader>/           :lua require('telescope.builtin').live_grep()<cr>
    nnoremap <leader>sd          :lua require('telescope.builtin').diagnostics()<cr>
    nnoremap <leader><leader>q   :lua require("volcano.telescope").toggle_quickfix()<cr>

" Diagnostic keymaps
    nnoremap [d                  :lua vim.diagnostic.goto_prev()<cr>zz
    nnoremap ]d                  :lua vim.diagnostic.goto_next()<cr>zz
    nnoremap <leader>e           :lua vim.diagnostic.open_float()<cr>
    nnoremap <leader>q           :lua vim.diagnostic.setqflist()<cr>

" Last_nth_buffer 
    nnoremap <silent> S          :lua require("volcano.last_nth_bfr").last_nth_buffer(3)()<cr>zz
    nnoremap <silent> gs         :lua require("volcano.last_nth_bfr").last_nth_buffer(4)()<cr>zz
    nnoremap <silent> gS         :lua require("volcano.last_nth_bfr").last_nth_buffer(5)()<cr>zz
    nnoremap <silent> <leader>gs :lua require("volcano.last_nth_bfr").last_nth_buffer(6)()<cr>zz
    nnoremap <silent> <leader>gS :lua require("volcano.last_nth_bfr").last_nth_buffer(7)()<cr>zz
    nnoremap <silent> <leader>Gs :lua require("volcano.last_nth_bfr").last_nth_buffer(8)()<cr>zz
    nnoremap <silent> <leader>GS :lua require("volcano.last_nth_bfr").last_nth_buffer(9)()<cr>zz

" LSP - more command are in lsp.lua I dont use them
    nnoremap <leader>rn          :lua vim.lsp.buf.rename()<cr>
    nnoremap <leader>ca          :lua vim.lsp.buf.code_action()<cr>
    nnoremap gd                  :lua vim.lsp.buf.definition()<cr>
    nnoremap gr                  :lua require('telescope.builtin').lsp_references()<cr>
    nnoremap <leader>D           :lua vim.lsp.buf.type_definition()<cr>
    nnoremap <leader>ds          :lua require('telescope.builtin').lsp_document_symbols()<cr>
    nnoremap gD                  :lua vim.lsp.buf.declaration()<cr>
    " nnoremap K                   :lua vim.lsp.buf.hover()<cr>
    nnoremap gk                  :lua vim.lsp.buf.signature_help()<cr>


"Format
    " nnoremap <leader>F           :Format<cr>

"Git Signs
    nnoremap <leader>gp          :lua require('gitsigns').prev_hunk<cr>
    nnoremap <leader>gn          :lua require('gitsigns').next_hunk<cr>
    nnoremap <leader>ph          :lua require('gitsigns').preview_hunk<cr>

" TODO
    nnoremap <leader>qt          :TodoQuickFix<cr>
