screenshot-directory=~/Pictures/
sub-bold=yes
sub-auto=fuzzy
screenshot-template="%F-%n-%p"
save-position-on-quit=yes
ytdl-format=bv[height<=1080]+ba[ext=m4a]/b[height<=1080]
# force-window=immediate
keep-open=yes
# fullscreen=yes
script-opts=ytsub-source_lang=en
no-border
autofit=100%

cache=yes
cache-pause=yes
cache-pause-initial=yes
demuxer-max-bytes=20GiB
demuxer-max-back-bytes=1GiB
cache-secs=86400
