screenshot-directory=~/Pictures/
sub-bold=yes
sub-auto=fuzzy
screenshot-template="%F-%n-%p"
save-position-on-quit=yes
ytdl-format=bv[height<=1080]+ba[ext=m4a]/b[height<=1080]
# force-window=immediate
keep-open=yes
# fullscreen=yes
script-opts=ytsub-source_lang=en
no-border
autofit=100%
